### ISSUE TITLE
Followed prerequisites.  Same 142 columns in each parquet with the same primary key.  Got this error:

### ISSUE THREAD

**Issue by janosek** [tharun026/SparkDataReconciler#1]
java.lang.NullPointerException: Value at index 0 is null
        at org.apache.spark.sql.Row$class.getAnyValAs(Row.scala:472)
        at org.apache.spark.sql.Row$class.getLong(Row.scala:231)
        at org.apache.spark.sql.catalyst.expressions.GenericRow.getLong(rows.scala:166)
        at com.github.tharun.datareconciler.transformers.Reconciler$$anonfun$reconcileDataFrames$1.apply(Reconciler.scala:48)
        at com.github.tharun.datareconciler.transformers.Reconciler$$anonfun$reconcileDataFrames$1.apply(Reconciler.scala:47)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at com.github.tharun.datareconciler.transformers.Reconciler$.reconcileDataFrames(Reconciler.scala:46)
        at com.github.tharun.datareconciler.plumbing.Reconciler.execute(Reconciler.scala:19)
        at com.github.tharun.datareconciler.plumbing.Command.runPipeline(Command.scala:27)
        at com.github.tharun.datareconciler.Pipeline$.main(Pipeline.scala:26)
        at com.github.tharun.datareconciler.Pipeline.main(Pipeline.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:847)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:922)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:931)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
21/12/06 15:24:20 ERROR plumbing.Reconciler: Value at index 0 is null
[Ljava.lang.StackTraceElement;@75c9ebca
Exception in thread "main" java.lang.IllegalStateException: Pipeline returned non success code: 2
        at com.github.tharun.datareconciler.Pipeline$.main(Pipeline.scala:30)
        at com.github.tharun.datareconciler.Pipeline.main(Pipeline.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:847)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:922)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:931)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by janosek** [comment]
Figured it out.  I have mixed data and the full primary key is has null values on some columns.  I isolated different subsets with non-null primary keys and it worked.

**Comment by tharun026** [comment]
Thanks @janosek for your interest.
